[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "icons-resource-bank"
description = "A Python wrapper for the Discord user API"
readme = "README.md"
version = "0.0.1"
requires-python = ">=3.11"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }

[tool.black]
line-length = 125
fast = true

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 125

[tool.pyright]
include = ["api"]
exclude = ["**/__pycache__", "build", "dist", "docs"]
reportUnnecessaryTypeIgnoreComment = "warning"
reportUnusedImport = "error"
reportShadowedImports = false
pythonVersion = "3.11"
typeCheckingMode = "basic"

[tool.pytest.ini_options]
asyncio_mode = "strict"
